import { Transaction, Milestone, ElderAdvisor } from './types';

export const mockTransactions: Transaction[] = [
  {
    id: 'tx-001',
    contributorName: 'Oumar T.',
    amount: 1000,
    date: '2023-10-15T10:00:00Z',
    method: 'zelle',
    status: 'cleared',
    receiptNumber: 'BH-REC-2023-0001',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Initial pledge',
  },
  {
    id: 'tx-002',
    contributorName: 'Anonymous Member',
    amount: 500,
    date: '2023-10-20T14:30:00Z',
    method: 'cash',
    status: 'verified',
    receiptNumber: 'BH-REC-2023-0002',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Cash donation at general assembly',
  },
  {
    id: 'tx-003',
    contributorName: 'Fatou K.',
    amount: 250,
    date: '2023-11-01T09:15:00Z',
    method: 'card',
    status: 'cleared',
    receiptNumber: 'BH-REC-2023-0003',
    verifiedBy: 'System',
    notes: 'Monthly sustaining pledge',
  },
  {
    id: 'tx-004',
    contributorName: 'Ibrahim S.',
    amount: 5000,
    date: '2023-11-15T16:45:00Z',
    method: 'check',
    status: 'cleared',
    receiptNumber: 'BH-REC-2023-0004',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Major contribution towards down payment',
  },
  {
    id: 'tx-005',
    contributorName: 'Awa C.',
    amount: 100,
    date: '2023-12-05T11:20:00Z',
    method: 'zelle',
    status: 'cleared',
    receiptNumber: 'BH-REC-2023-0005',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Standard family pledge',
  },
  {
    id: 'tx-006',
    contributorName: 'Amadou B.',
    amount: 300,
    date: '2023-12-10T13:10:00Z',
    method: 'cash',
    status: 'verified',
    receiptNumber: 'BH-REC-2023-0006',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Collected at community meeting',
  },
  {
    id: 'tx-007',
    contributorName: 'Mariam D.',
    amount: 150,
    date: '2024-01-12T08:00:00Z',
    method: 'card',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0007',
    verifiedBy: 'System',
    notes: 'Monthly pledge',
  },
  {
    id: 'tx-008',
    contributorName: 'Seydou N.',
    amount: 2000,
    date: '2024-02-01T10:30:00Z',
    method: 'ach',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0008',
    verifiedBy: 'System',
    notes: 'Bank transfer',
  },
  {
    id: 'tx-009',
    contributorName: 'Kadiatou F.',
    amount: 100,
    date: '2024-02-15T15:45:00Z',
    method: 'zelle',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0009',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Standard family pledge',
  },
  {
    id: 'tx-010',
    contributorName: 'Anonymous Member',
    amount: 1000,
    date: '2024-03-01T12:00:00Z',
    method: 'cash',
    status: 'verified',
    receiptNumber: 'BH-REC-2024-0010',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Anonymous cash donation',
  },
  {
    id: 'tx-011',
    contributorName: 'Ousmane L.',
    amount: 50,
    date: '2024-03-20T09:30:00Z',
    method: 'card',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0011',
    verifiedBy: 'System',
    notes: 'Sustaining member pledge',
  },
  {
    id: 'tx-012',
    contributorName: 'Bintou M.',
    amount: 250,
    date: '2024-04-05T14:15:00Z',
    method: 'zelle',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0012',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Builder pledge',
  },
  {
    id: 'tx-013',
    contributorName: 'Salif K.',
    amount: 1500,
    date: '2024-05-10T11:00:00Z',
    method: 'check',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0013',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Check deposited in escrow',
  },
  {
    id: 'tx-014',
    contributorName: 'Aminata S.',
    amount: 100,
    date: '2024-06-01T08:45:00Z',
    method: 'card',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0014',
    verifiedBy: 'System',
    notes: 'Standard family pledge',
  },
  {
    id: 'tx-015',
    contributorName: 'Anonymous Member',
    amount: 200,
    date: '2024-06-15T16:30:00Z',
    method: 'cash',
    status: 'verified',
    receiptNumber: 'BH-REC-2024-0015',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Cash donation',
  },
  {
    id: 'tx-016',
    contributorName: 'Moussa T.',
    amount: 500,
    date: '2024-07-05T10:15:00Z',
    method: 'zelle',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0016',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Donation',
  },
  {
    id: 'tx-017',
    contributorName: 'Hawa B.',
    amount: 50,
    date: '2024-07-20T13:00:00Z',
    method: 'card',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0017',
    verifiedBy: 'System',
    notes: 'Sustaining member',
  },
  {
    id: 'tx-018',
    contributorName: 'Lamine D.',
    amount: 1000,
    date: '2024-08-01T09:00:00Z',
    method: 'ach',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0018',
    verifiedBy: 'System',
    notes: 'Direct transfer',
  },
  {
    id: 'tx-019',
    contributorName: 'Fatim C.',
    amount: 250,
    date: '2024-08-15T14:45:00Z',
    method: 'zelle',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0019',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Builder pledge',
  },
  {
    id: 'tx-020',
    contributorName: 'Boubacar N.',
    amount: 300,
    date: '2024-09-01T11:30:00Z',
    method: 'cash',
    status: 'pending',
    receiptNumber: 'BH-REC-2024-0020',
    verifiedBy: 'Mamadou O. (Treasurer)',
    notes: 'Pending verification',
  },
  {
    id: 'tx-021',
    contributorName: 'Adama F.',
    amount: 100,
    date: '2024-09-10T16:00:00Z',
    method: 'card',
    status: 'cleared',
    receiptNumber: 'BH-REC-2024-0021',
    verifiedBy: 'System',
    notes: 'Standard family pledge',
  }
];

export const mockMilestones: Milestone[] = [
  {
    id: 'm-1',
    title: 'Phase 1: 20% Commercial Down Payment & Escrow',
    targetAmount: 150000,
    currentAmount: 24750,
    deadline: '2026-12-31T23:59:59Z',
  },
];

export const mockElders: ElderAdvisor[] = [
  {
    name: 'El Hadj Oumar C.',
    role: 'Head of Elder Advisory Board',
    communityAffiliation: 'Newark Islamic Center',
    statement: 'This project is for our children. Transparency and trust are our foundation.',
  },
  {
    name: 'Mme. Aissata K.',
    role: 'Community Matriarch & Board Member',
    communityAffiliation: 'Burkina Women\'s Association of NJ',
    statement: 'We are building a legacy that will serve generations to come.',
  },
  {
    name: 'Dr. Seydou T.',
    role: 'Financial Oversight Advisor',
    communityAffiliation: 'Essex County Professionals',
    statement: 'Rigorous financial controls ensure every dollar is accounted for.',
  },
];
